### ISSUE TITLE
[Idea] Support for auto pipelining

### ISSUE THREAD

**Issue by pfreixes** [pfreixes/emcache#46]
Based on the research done by @mcollina here [1] Emcache could also provide an auto pipelining execution mode where gets would be sent and received at each loop iteration implementing a kind of micro batching pattern.

The unique operation supported for now would be `get` which is supported in batched mode by Memcached.

We must create as many batches as many different nodes would be participating in the cluster, behind the scenes Emcache will be responsible for grouping all of the keys to each micro-batch and send each of them at each loop iteration.

Some configuration values that could be exposed to the user:

- Batch size.
- Batch timeout.
- Max batch concurrency per loop iteration.

[1] https://github.com/mcollina/ioredis-auto-pipeline

**Comment by mcollina** [comment]
Count me in if you need to review the implementation.

**Comment by pfreixes** [comment]
@mcollina In case you want to review the implementation, there is.a final proposal in this PR https://github.com/pfreixes/emcache/pull/57. Still some details to be polished, mainly documentation, but this should be pretty much the final implementation.

**Comment by pfreixes** [comment]
Implemented and merged
