### ISSUE TITLE
[bug] handle remove_waiter that is not there

### ISSUE THREAD

**Issue by lferran** [pfreixes/emcache#48]
I'm seeing this in logs sometimes:
```
CancelledError: null
  File "emcache/connection_pool.py", line 367, in __aenter__
    self._connection = await self._waiter

ValueError: deque.remove(x): x not in deque
...

  File "emcache/client.py", line 319, in set
    result = await self._storage_command(b"set", key, value, flags, exptime, noreply)
  File "emcache/client.py", line 114, in _storage_command
    async with node.connection() as connection:
  File "emcache/connection_pool.py", line 369, in __aenter__
    self._connection_pool.remove_waiter(self._waiter)
  File "emcache/connection_pool.py", line 309, in remove_waiter
    self._waiters.remove(waiter)

```

**Comment by pfreixes** [comment]
Seems that this is a serious bug, TBH I do not know how you ended up by not having a connection leaking problem here. Unless this is happening but happens not to much frequently and connections are purged or eventually closed by the server, while there is still room for new connections.

The bug could be related to the fact that a task that has been resumed or asked to be resumed in the next loop iteration, can be still be canceled within the same loop iteration, take a look to this [1] and this [2].

As an example of what could be happening

```python
import asyncio

async def task(future):
    try:
        result = await future
    except asyncio.CancelledError:
        print("*"*30)
        print(future.result())
        raise


async def main():
    future = asyncio.get_running_loop().create_future()
    t = asyncio.ensure_future(task(future))
    await asyncio.sleep(0)
    future.set_result("fooooooooooooooo")
    t.cancel()
    await t

asyncio.run(main())
```
Now replace `fooooooooooo` by a connection instance, the result would be a connection leak. With the waiter being already removed initially during the first attempt for waking up the task.

This needs to be fixed. I'll make some comments to your PR https://github.com/pfreixes/emcache/pull/49 about what are my thoughts

[1] https://github.com/python/cpython/blob/master/Lib/asyncio/tasks.py#L234
[2] https://github.com/python/cpython/blob/master/Lib/asyncio/tasks.py#L243
